title: "Actix Blog"
description: "A blog about stuff"
default: rust-is-hard
posts:
  - slug: microservices
    title: "Workflow with k3s"
    author: Neil Ulises
    date: 2022-10-23
    body: >
      Is intimidating test thing in production and always ask how can do it 
      easy with all the best practices and CI/CD.
      In this guide we're going to use sqlite, k3s and htmx to ship software
      fast and reliable, a
      ```sh
        k config set-cluster my-k3s-cluster --server=https://127.0.0.1:6443 --insecure-skip-tls-verify
      ```
  - slug: rust-is-hard
    title: "Rust is hard"
    author: Github Copilot
    date: 2022-10-23
    body: >
      [link](https://github.com)
      I've been trying to learn Rust for a while now, but I just can't get it.
      I've tried reading the book, but it's just so dry. I've tried watching
      videos, but they're all so long. I've tried reading blog posts, but they
      all seem to be written by people who already know Rust. I've tried
      reading the source code, but it's just so hard to understand. I've tried
      reading the RFCs, but they're all so long. I've tried reading the
      documentation, but it's just so hard to understand. I've tried reading
      the book again, but it's just so dry. I've tried watching videos again,
      but they're all so long. I've tried reading blog posts again, but they
      all seem to be written by people who already know Rust. I've tried
      reading the source code again, but it's just so hard to understand. I've
      tried reading the RFCs again, but they're all so long. I've tried reading
      the documentation again, but it's just so hard to understand. I've tried
      reading the book again, but it's just so dry. I've tried watching videos
      again, but they're all so long. I've tried reading blog posts again, but
      they all seem to be written by people who already know Rust. I've tried
      reading the source code again, but it's just so hard to understand. I've
      tried reading the RFCs again, but they're all so long. I've tried reading
      the documentation again, but it's just so hard to understand. I've tried
      reading the book again, but it's just so dry. I've tried watching videos
      again, but they're all so long. I've tried reading blog posts again, but
      they all seem to be written by people who already know Rust. I've tried
      reading the source code again, but it's just so hard to understand. I've
      tried reading the RFCs again, but they're all so long. I've tried reading
      the documentation again, but it's just so hard to understand. I've tried
      reading the book again, but it's just so dry. I've tried watching videos
      again, but they're all
      ![tree](/images/logo.png)

      ```rust
        use std::net::TcpListener;
        use demcru::startup::run;
        use demcru::configuration::get_config;
        use sqlx::PgPool;

        #[tokio::main]
        async fn main() -> std::io::Result<()> {
            let config = get_config().expect("Failed to read config");
            let connection_pool = PgPool::connect(&config.database.connection_string())
                .await
                .expect("Failed to connect to postgres.");
            let address = format!("127.0.0.1:{}", config.application_port);
            let listener = TcpListener::bind(address)?;
            run(listener, connection_pool)?.await?;
            Ok(())
        }
      ```
  - slug: build-fullstack
    title: "Develop and ship good software"
    author: Neil Campos
    date: 2023-11-07
    body: >
      ## htmx, k3s, rust, tailwind and turso.

      This is only a list that is useful to me when I need to build a full app
      and not pretend to tell you what tool to use. 
      Yep htmx sounds like another library but is really simple be productive and 
      have good practices with your API and a standar to change the dom directly
      with HTML, even the react frameworks noticed that its more convenient use
      server components and locality of behavior and explote all the boundaries
      that the server offer; React it's to much complexity that you rarely need,
      and that forces you to maintain 2 codebases. Am only suggesting that instead
      of that you master and adopt the HATEOAS in the language you like. 
      it's a good choice to prototype user interfaces really
      quickly. 

      ## k3s

      There are many advantages to running an on premises kubernates cluster, it
      can increase performance, lower cost giving you the portability and the 
      scalability that's assoiciated with cloud native applications.

      A lot for a simple developer like me that in the first time that install k8s
      and use it to deploy a little server with a database was overwhelming that why
      I opted for k3s, It gives you all preconfigured in a single binary of about 45MB
      that completely implements the Kubernates API's. To ensure lightness they
      removed a lot of extra drivers that are not strictly part of the core, but
      still easily replaceable with external add ons.

      ## Downsides of k8s complexity

      Etcd, Load Balancers, High Availability, Networking,
      Persistent Storage, Internal Certificate rotation and distributions.
      And added to this there is the inherent complexity of running such a large
      orchestration application, so running:
      kube apiserver, kube proxy, kube scheduler, kube controller manager,
      kubelet

      ## What k3s does for you

      Internally managed Etcd cluster, Internally managed TLS communications,
      Internally managed certificate rotation and distribution,
      Integrated storage provider(localpath provisioner), Low dependency on base operating system.
      ![arch](/images/arch.svg)
